### ISSUE TITLE
it crashes when I right click a FitSZerosuit

### ISSUE THREAD

**Issue by BrawlCrate** [BrawlCrate/BrawlCrateIssues#100]
v0.30c x86
```
Unable to cast object of type 'BrawlLib.SSBB.ResourceNodes.MasqueradeEntryNode' to type 'BrawlLib.SSBB.ResourceNodes.CSSCEntryNode'.
   at BrawlCrate.NodeWrappers.MasqueradeEntryWrapper.MenuOpening(Object sender, CancelEventArgs e)
   at System.Windows.Forms.ToolStripDropDown.OnOpening(CancelEventArgs e)
   at System.Windows.Forms.ToolStripDropDown.SetVisibleCore(Boolean visible)
   at System.Windows.Forms.ContextMenuStrip.SetVisibleCore(Boolean visible)
   at System.Windows.Forms.ToolStripDropDown.Show(Control control, Point position)
   at System.Windows.Forms.ToolStripDropDown.Show(Control control, Int32 x, Int32 y)
   at BrawlCrate.UI.ResourceTree.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

**Comment by soopercool101** [comment]
Fixed in https://github.com/soopercool101/BrawlCrate/commit/8b2b94f5332ea427dc64bee8ce36307b708ac938
