### ISSUE TITLE
0.30e h1 not opening

### ISSUE THREAD

**Issue by BrawlCrate** [BrawlCrate/BrawlCrateIssues#107]
i just tried opening the new version

v0.30e-h1 x86
```
The type initializer for 'BrawlCrate.API.BrawlAPIInternal' threw an exception. Could not load file or assembly 'Microsoft.Scripting, Version=1.2.2.0, Culture=neutral, PublicKeyToken=7f709c5b713576e1' or one of its dependencies. The system cannot find the file specified.
   at BrawlCrate.API.BrawlAPIInternal.get_Plugins()
   at BrawlCrate.UI.MainForm..ctor()
   at BrawlCrate.UI.MainForm.get_Instance()
   at BrawlCrate.Program.Main(String[] args)
```

**Comment by soopercool101** [comment]
Missing DLL. Likely caused by antivirus. Unfixable from my end
