### ISSUE TITLE
I can't use it

### ISSUE THREAD

**Issue by BrawlCrate** [BrawlCrate/BrawlCrateIssues#108]
I updated brawlcrate but I can't access it

v0.30e-h1 x86
```
The type initializer for 'BrawlLib.SSBB.ResourceNodes.MDL0TextureNode' threw an exception. Could not load file or assembly 'OpenTK, Version=1.0.0.0, Culture=neutral, PublicKeyToken=bad199fe84eb3df4' or one of its dependencies. The module was expected to contain an assembly manifest.
   at BrawlLib.Internal.Windows.Controls.Model_Panel.ModelPanel..ctor()
   at BrawlLib.Internal.Windows.Controls.MDL0ObjectControl.InitializeComponent()
   at BrawlLib.Internal.Windows.Controls.MDL0ObjectControl..ctor()
   at BrawlCrate.UI.MainForm.InitializeComponent()
   at BrawlCrate.UI.MainForm..ctor()
   at BrawlCrate.UI.MainForm.get_Instance()
   at BrawlCrate.Program.Close(Boolean force)
   at BrawlCrate.Program.Open(String path, Boolean showErrors)
   at BrawlCrate.Program.Main(String[] args)
```

**Comment by soopercool101** [comment]
Missing OpenTK DLL, likely due to antivirus. Cannot be fixed on my end, please do a fresh reinstall.
