### ISSUE TITLE
Test

### ISSUE THREAD

**Issue by BrawlCrate** [BrawlCrate/BrawlCrateIssues#115]
Test of new issue reporting functionality

v0.30g x86
```
The volume for a file has been externally altered so that the opened file is no longer valid. (Exception from HRESULT: 0x800703EE)
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHR(Int32 errorCode)
   at BrawlLib.Platform.Win32.SafeHandle.ErrorCheck() in C:\git\BrawlCrate\BrawlLib\Platform\Win32.cs:line 39
   at BrawlLib.Internal.IO.wFileMap..ctor(VoidPtr hFile, FileMapProtect protect, Int64 offset, UInt32 length) in C:\git\BrawlCrate\BrawlLib\Internal\IO\FileMap.cs:line 202
   at BrawlLib.Internal.IO.FileMap.FromStreamInternal(FileStream stream, FileMapProtect prot, Int32 offset, Int32 length) in C:\git\BrawlCrate\BrawlLib\Internal\IO\FileMap.cs:line 162
   at BrawlLib.Internal.IO.FileMap.FromFile(String path, FileMapProtect prot, Int32 offset, Int32 length, FileOptions options) in C:\git\BrawlCrate\BrawlLib\Internal\IO\FileMap.cs:line 89
   at BrawlLib.SSBB.ResourceNodes.NodeFactory.FromFile(ResourceNode parent, String path, FileOptions options, Type t) in C:\git\BrawlCrate\BrawlLib\SSBB\ResourceNodes\NodeFactory.cs:line 82
   at BrawlLib.SSBB.ResourceNodes.NodeFactory.FromFile(ResourceNode parent, String path, Type t) in C:\git\BrawlCrate\BrawlLib\SSBB\ResourceNodes\NodeFactory.cs:line 71
   at BrawlCrate.NodeWrappers.GenericWrapper.Duplicate(Boolean changeName) in C:\git\BrawlCrate\BrawlCrate\NodeWrappers\GenericWrapper.cs:line 395
   at BrawlCrate.NodeWrappers.GenericWrapper.Duplicate() in C:\git\BrawlCrate\BrawlCrate\NodeWrappers\GenericWrapper.cs:line 382
   at BrawlCrate.NodeWrappers.GenericWrapper.DuplicateAction(Object sender, EventArgs e) in C:\git\BrawlCrate\BrawlCrate\NodeWrappers\GenericWrapper.cs:line 96
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStripMenuItem.ProcessCmdKey(Message& m, Keys keyData)
   at System.Windows.Forms.ToolStripManager.ProcessShortcut(Message& m, Keys shortcut)
   at System.Windows.Forms.ToolStripManager.ProcessCmdKey(Message& m, Keys keyData)
   at System.Windows.Forms.ContainerControl.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.Form.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.Control.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.ContainerControl.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.Control.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.Control.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.Control.PreProcessMessage(Message& msg)
   at System.Windows.Forms.Control.PreProcessControlMessageInternal(Control target, Message& msg)
   at System.Windows.Forms.Application.ThreadContext.PreTranslateMessage(MSG& msg)
```

**Comment by soopercool101** [comment]
Test successful
