### ISSUE TITLE
Arithmetic operation resulted in an overflow.

### ISSUE THREAD

**Issue by BrawlCrate** [BrawlCrate/BrawlCrateIssues#122]
I merely replaced a module in the common3 before trying to save. BrawlCrate then threw an error saying "Arithmetic operation resulted in an overflow." and asked if I wanted to submit a report.

BrawlCrate Canary #d3ce3a511c15213ee77429a507082d07c7f8d699 x86
```
Arithmetic operation resulted in an overflow.
   at BrawlLib.Internal.VoidPtr.MinusUL(VoidPtr p1, VoidPtr p2)
   at BrawlLib.SSBB.ResourceNodes.ResourceNode.MoveRaw(VoidPtr address, Int32 length)
   at BrawlLib.SSBB.ResourceNodes.ResourceNode.Rebuild(VoidPtr address, Int32 length, Boolean force)
   at BrawlLib.SSBB.ResourceNodes.ARCNode.OnRebuild(VoidPtr address, Int32 size, Boolean force)
   at BrawlLib.SSBB.ResourceNodes.ResourceNode.Rebuild(VoidPtr address, Int32 length, Boolean force)
   at BrawlLib.SSBB.ResourceNodes.ResourceNode.Rebuild(Boolean force)
   at BrawlLib.SSBB.ResourceNodes.ResourceNode.Merge(Boolean forceBuild)
   at BrawlCrate.Program.Save()
   at BrawlCrate.UI.MainForm.saveToolStripMenuItem_Click(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

**Comment by soopercool101** [comment]
Fixed in soopercool101/BrawlCrate@db9e5a5c7dca56fc5c5cf42379e2b117fdf7c145
