### ISSUE TITLE
selecting an object which references a deleted material

### ISSUE THREAD

**Issue by BrawlCrate** [BrawlCrate/BrawlCrateIssues#13]
deleted a material then opened the object. oops

BrawlCrateCanary#80acbc4d18079224e919c989402920f4c45b2d0e
Object reference not set to an instance of an object.
   at System.Windows.Forms.MDL0ObjectControl.SetTarget(MDL0ObjectNode o)
   at BrawlCrate.MainForm.resourceTree_SelectionChanged(Object sender, EventArgs e)
   at BrawlCrate.ResourceTree.set_SelectedNode(TreeNode value)
   at BrawlCrate.ResourceTree.OnAfterSelect(TreeViewEventArgs e)
   at System.Windows.Forms.TreeView.TvnSelected(NMTREEVIEW* nmtv)
   at System.Windows.Forms.TreeView.WmNotify(Message& m)
   at System.Windows.Forms.TreeView.WndProc(Message& m)
   at BrawlCrate.ResourceTree.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by soopercool101** [comment]
Should be fixed as of https://github.com/soopercool101/BrawlCrate/commit/b3fde345bc2048d011678945025a8399f8db7f6b
