### ISSUE TITLE
sc_selcharacter.pac

### ISSUE THREAD

**Issue by BrawlCrate** [BrawlCrate/BrawlCrateIssues#140]
i just open sc_selcharacter.pac

v0.31-h1 x86
```
Failed to save settings: An error occurred loading a configuration file: There is not enough space on the disk.
 (C:\Users\Daniel\AppData\Local\BrawlCrate\BrawlCrate.exe_Url_fc4vouml0pc5dlleniiueuw0ijkbexmr\0.31.0.1\user.config) An error occurred loading a configuration file: There is not enough space on the disk.
 (C:\Users\Daniel\AppData\Local\BrawlCrate\BrawlCrate.exe_Url_fc4vouml0pc5dlleniiueuw0ijkbexmr\0.31.0.1\user.config)
   at System.Configuration.ClientSettingsStore.WriteSettings(String sectionName, Boolean isRoaming, IDictionary newSettings)
   at System.Configuration.LocalFileSettingsProvider.SetPropertyValues(SettingsContext context, SettingsPropertyValueCollection values)
   at System.Configuration.SettingsBase.SaveCore()
   at System.Configuration.SettingsBase.Save()
   at System.Configuration.ApplicationSettingsBase.Save()
   at BrawlLib.Internal.Windows.Controls.AudioPlaybackPanel.set_VolumePercent(Nullable`1 value)
   at BrawlLib.Internal.Windows.Controls.AudioPlaybackPanel..ctor()
   at BrawlCrate.UI.MainForm.InitializeComponent()
   at BrawlCrate.UI.MainForm..ctor()
   at BrawlCrate.UI.MainForm.get_Instance()
   at BrawlCrate.Program.Close(Boolean force)
   at BrawlCrate.Program.Open(String path, Boolean showErrors)
   at BrawlCrate.Program.Main(String[] args)
```

**Comment by soopercool101** [comment]
Not a BrawlCrate issue. User needs more hard drive space on their C:\ drive.
