### ISSUE TITLE
huh

### ISSUE THREAD

**Issue by BrawlCrate** [BrawlCrate/BrawlCrateIssues#160]
???
I don't know what the bug is

v0.34-h3 x86
i literally just tried to open it and it didn't open

v0.32-h1 x86
```
The type initializer for 'BrawlLib.SSBB.ResourceNodes.MDL0TextureNode' threw an exception. Could not load file or assembly 'OpenTK, Version=1.0.0.0, Culture=neutral, PublicKeyToken=bad199fe84eb3df4' or one of its dependencies. The module was expected to contain an assembly manifest.
   at BrawlLib.Internal.Windows.Controls.Model_Panel.ModelPanel..ctor()
   at BrawlLib.Internal.Windows.Controls.MDL0ObjectControl.InitializeComponent()
   at BrawlLib.Internal.Windows.Controls.MDL0ObjectControl..ctor()
   at BrawlCrate.UI.MainForm.InitializeComponent()
   at BrawlCrate.UI.MainForm..ctor()
   at BrawlCrate.UI.MainForm.get_Instance()
   at BrawlCrate.Program.Main(String[] args)
```

**Comment by soopercool101** [comment]
OpenTK Error
