### ISSUE TITLE
Using *Import Existing Object*

### ISSUE THREAD

**Issue by BrawlCrate** [BrawlCrate/BrawlCrateIssues#19]
Export model as mdl0, tried to use import existing object, but throws this error

~ Ampharos 2.0

BrawlCrate Canary@brawlcrate-master #65177077b05df413cd28fc7d47f763d1160fb1eb
Unable to cast object of type 'BrawlLib.SSBB.ResourceNodes.MDL0GroupNode' to type 'BrawlLib.Modeling.IMatrixNode'.
   at System.Windows.Forms.ObjectImporter.GetBaseInfluence()
   at System.Windows.Forms.ObjectImporter.comboBox1_SelectedIndexChanged(Object sender, EventArgs e)
   at System.Windows.Forms.ComboBox.OnSelectedIndexChanged(EventArgs e)
   at System.Windows.Forms.ComboBox.set_SelectedIndex(Int32 value)
   at System.Windows.Forms.ObjectImporter.ShowDialog(MDL0Node internalModel, MDL0Node externalModel)
   at BrawlCrate.NodeWrappers.MDL0Wrapper.ImportObject()
   at BrawlCrate.NodeWrappers.MDL0Wrapper.ImportObjectAction(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by soopercool101** [comment]
Functionality doesn't work for non v9 MDL0. Brawl Functionality not affected by bug
