### ISSUE TITLE
Oopsie Doopsie. I made a fucky wucky

### ISSUE THREAD

**Issue by BrawlCrate** [BrawlCrate/BrawlCrateIssues#211]
I was just trying to play the preview of a brstm I got off Smashcustommusic.net, specifically the looped version of Theme of Captain Falcon from F-Zero GX

v0.34-h3 x86
```
Object reference not set to an instance of an object.
   at BrawlLib.Internal.Windows.Controls.AudioPlaybackPanel.UpdateTimeDisplay()
   at BrawlLib.Internal.Windows.Controls.AudioPlaybackPanel.trackBar1_ValueChanged(Object sender, EventArgs e)
   at System.Windows.Forms.TrackBar.OnValueChanged(EventArgs e)
   at System.Windows.Forms.TrackBar.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

**Comment by Enerzma** [comment]
I wouldn't have named it that if I realized it would be posted on the github. I guess I truly did make a fucky wucky huh

**Comment by soopercool101** [comment]
Lmao
