### ISSUE TITLE
getting this error when exporting dae

### ISSUE THREAD

**Issue by BrawlCrate** [BrawlCrate/BrawlCrateIssues#34]
this never has happened before. ever. it doesn't export correctly, model doesn't show up in 3ds max

BrawlCrate Canary@brawlcrate-master #d2fa525774dd6d5d51d275f30eac107204eecf4d
Index was outside the bounds of the array.
   at BrawlLib.Modeling.Collada.WritePolyInstance(DrawCall c, XmlWriter writer)
   at BrawlLib.Modeling.Collada.WriteNodes(MDL0Node model, XmlWriter writer)
   at BrawlLib.Modeling.Collada.Serialize(MDL0Node model, String outFile)
   at BrawlLib.SSBB.ResourceNodes.MDL0Node.Export(String outPath)
   at BrawlCrate.GenericWrapper.OnExport(String outPath, Int32 filterIndex)
   at BrawlCrate.GenericWrapper.Export()
   at BrawlCrate.GenericWrapper.ExportAction(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by soopercool101** [comment]
Fixed as of commit soopercool101/BrawlCrate@f2a879ecc857adb189fb78ef00cf50ee42cb7dcd
