### ISSUE TITLE
tried importing texture

### ISSUE THREAD

**Issue by BrawlCrate** [BrawlCrate/BrawlCrateIssues#39]
BrawlCrate Canary@brawlcrate-master #aae3bf22bac436c9bf9dc9fa2d8341849bb86d3b
Parameter is not valid.
   at System.Drawing.Bitmap..ctor(Int32 width, Int32 height, Int32 stride, PixelFormat format, IntPtr scan0)
   at System.Windows.Forms.TextureConverterDialog.LoadImagesPreservingPaletteInfo(String path)
   at System.Windows.Forms.TextureConverterDialog.LoadImages(String path)
   at System.Windows.Forms.TextureConverterDialog.OnShown(EventArgs e)
   at System.Windows.Forms.Form.CallShownEvent()
   at System.Windows.Forms.Control.InvokeMarshaledCallbackDo(ThreadMethodEntry tme)
   at System.Windows.Forms.Control.InvokeMarshaledCallbackHelper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Forms.Control.InvokeMarshaledCallback(ThreadMethodEntry tme)
   at System.Windows.Forms.Control.InvokeMarshaledCallbacks()

**Comment by soopercool101** [comment]
Fixed in soopercool101/BrawlCrate@af33fc94cf9f7bf1d8a9f67e27e8f07916218f83
