### ISSUE TITLE
deleting polys

### ISSUE THREAD

**Issue by BrawlCrate** [BrawlCrate/BrawlCrateIssues#41]
deleting fludd polys does this idk

BrawlCrate_v0.25bHotfix1
Object reference not set to an instance of an object.
   at System.Windows.Forms.MDL0ObjectControl.SetTarget(MDL0ObjectNode o)
   at BrawlCrate.MainForm.resourceTree_SelectionChanged(Object sender, EventArgs e)
   at BrawlCrate.ResourceTree.set_SelectedNode(TreeNode value)
   at BrawlCrate.ResourceTree.OnAfterSelect(TreeViewEventArgs e)
   at System.Windows.Forms.TreeView.TvnSelected(NMTREEVIEW* nmtv)
   at System.Windows.Forms.TreeView.WmNotify(Message& m)
   at System.Windows.Forms.TreeView.WndProc(Message& m)
   at BrawlCrate.ResourceTree.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by soopercool101** [comment]
Couldn't replicate but I just put a check in place to ensure that a null reference there won't screw up the previewer. Should be fixed.
