### ISSUE TITLE
Memory Editor Crash

### ISSUE THREAD

**Issue by BrawlCrate** [BrawlCrate/BrawlCrateIssues#5]
Opened memory editor for st_famicom.rel resulting in instant crash

BrawlCrate_v0.17
Length cannot be less than zero.
Parameter name: length
   at System.String.Substring(Int32 startIndex, Int32 length)
   at Be.Windows.Forms.HexBox.PaintHexStringSelected(Graphics g, Byte b, Int64 offset, Brush brush, Brush brushBack, Point gridPoint)
   at Be.Windows.Forms.HexBox.PaintHexAndStringView(Graphics g, Int64 startByte, Int64 endByte)
   at Be.Windows.Forms.HexBox.OnPaint(PaintEventArgs e)
   at System.Windows.Forms.Control.PaintWithErrorHandling(PaintEventArgs e, Int16 layer)
   at System.Windows.Forms.Control.WmPaint(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by soopercool101** [comment]
Fixed in https://github.com/soopercool101/BrawlCrate/commit/44250c93c873dfe50a1d211622299240e3697d9b
