### ISSUE TITLE
0.17  broke BRSTM creation

### ISSUE THREAD

**Issue by BrawlCrate** [BrawlCrate/BrawlCrateIssues#6]
Grab a wav that worked in a previous version and try to make a BRSTM with it, and Brawl Crate 0.17h1 will throw an error.

BrawlCrate_v0.17Hotfix1
Value cannot be null.
Parameter name: pointer
   at System.IO.UnmanagedMemoryStream.Initialize(Byte* pointer, Int64 length, Int64 capacity, FileAccess access, Boolean skipSecurityCheck)
   at System.IO.UnmanagedMemoryStream..ctor(Byte* pointer, Int64 length, Int64 capacity, FileAccess access)
   at BrawlCrate.MainForm.resourceTree_SelectionChanged(Object sender, EventArgs e)
   at BrawlCrate.ResourceTree.set_SelectedNode(TreeNode value)
   at BrawlCrate.ResourceTree.OnAfterSelect(TreeViewEventArgs e)
   at System.Windows.Forms.TreeView.TvnSelected(NMTREEVIEW* nmtv)
   at System.Windows.Forms.TreeView.WmNotify(Message& m)
   at System.Windows.Forms.TreeView.WndProc(Message& m)
   at BrawlCrate.ResourceTree.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by soopercool101** [comment]
Fixed in https://github.com/soopercool101/BrawlCrate/commit/0744c7ea2186c103fa4b5a112eef34771a4a5ebe
