### ISSUE TITLE
Crash on opening MKWii track szs

### ISSUE THREAD

**Issue by BrawlCrate** [BrawlCrate/BrawlCrateIssues#69]
I was literally just opening a MKWii track .szs file

BrawlCrate NEXT Canary #252537981119252021a01b402b681d1c82618b66 x64
The type initializer for 'BrawlCrate.API.BrawlAPI' threw an exception.
   at BrawlCrate.API.BrawlAPI.get_Plugins()
   at BrawlCrate.MainForm..ctor()
   at BrawlCrate.MainForm.get_Instance()
   at BrawlCrate.Program.Close(Boolean force)
   at BrawlCrate.Program.Open(String path, Boolean showErrors)
   at BrawlCrate.Program.Main(String[] args)

**Comment by soopercool101** [comment]
x64 builds are not officially supported at this time. This bug is likely related to that.
