### ISSUE TITLE
str0 crash

### ISSUE THREAD

**Issue by BrawlCrate** [BrawlCrate/BrawlCrateIssues#78]
tried to open a str0 animation iin GCN Waluigi Stadium model, MKWii

BrawlCrate NEXT Canary #e26f7b8fd80c8b7d8f74b16e0841ea3df3be0a57 x86
Object reference not set to an instance of an object.
   at BrawlLib.SSBB.ResourceNodes.MDL0TextureNode.GetSource()
   at BrawlLib.SSBB.ResourceNodes.MDL0TextureNode.Load(Int32 index, Int32 program, MDL0Node model, Boolean isMetal)
   at BrawlLib.SSBB.ResourceNodes.MDL0TextureNode.Prepare(MDL0MaterialRefNode mRef, Int32 shaderProgramHandle, String palette)
   at BrawlLib.SSBB.ResourceNodes.MDL0MaterialRefNode.Bind(Int32 prog)
   at BrawlLib.SSBB.ResourceNodes.MDL0ObjectNode.Render(Boolean wireframe, Boolean useShaders, MDL0MaterialNode material)
   at BrawlLib.SSBB.ResourceNodes.DrawCall.Render(ModelPanelViewport viewport)
   at System.Windows.Forms.ModelPanel.OnRenderViewport(PaintEventArgs e, GLViewport v)
   at BrawlLib.OpenGL.GLPanel.OnRender(PaintEventArgs e)
   at BrawlLib.OpenGL.GLPanel.OnPaint(PaintEventArgs e)
   at System.Windows.Forms.Control.PaintWithErrorHandling(PaintEventArgs e, Int16 layer)
   at System.Windows.Forms.Control.WmPaint(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.UserControl.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by soopercool101** [comment]
Fixed in https://github.com/soopercool101/BrawlCrateNext/commit/06cb11ea70a7e3bbe68727674d3d9160276c9d23
